[meta]
name = "iidx-3rd-style"
ansi_source = "Catppuccin Macchiato + IIDXSERIES"
booru = "beatmania_iidx_3rd_style"
signature = ["cursor", "selection", "foreground"]

[meta.booru_sites]
konachan = []
yande = []
zerochan = []

[colors]
background = "#1f1518"
foreground = "#e2e2e2"
cursor = "#c6487c"
selection_background = "#673752"
ansi = [
  "#2c2124",
  "#e68399",
  "#bbaf4c",
  "#f2ac7f",
  "#af93e2",
  "#d194b6",
  "#89b5de",
  "#d5c2c6",

  "#837377",
  "#f8acbc",
  "#d9cf7e",
  "#fdd5b8",
  "#ccb8f0",
  "#ffaed9",
  "#add6ff",
  "#ffe8ed",
]
