[meta]
name = "iidx-31-epolis"
ansi_source = "Catppuccin Macchiato + IIDXSERIES"
booru = "beatmania_iidx_31_epolis"
signature = ["cursor", "selection", "foreground"]

[meta.booru_sites]
konachan = []
yande = []
zerochan = []

[colors]
background = "#18180e"
foreground = "#e2e2e2"
cursor = "#d0da31"
selection_background = "#4e0e52"
ansi = [
  "#242419",
  "#e98563",
  "#95b669",
  "#cebb6f",
  "#35b0bb",
  "#dc8fa2",
  "#84bd96",
  "#c9c7b6",

  "#787869",
  "#fdad92",
  "#bad596",
  "#efdd8e",
  "#86cdd3",
  "#fdb1c3",
  "#a6dfb7",
  "#f0efd4",
]
