"$schema" = "https://www.schemastore.org/ttheme-palette.json"

[meta]
name = "iidx-13-distorted"
ansi_source = "Tomorrow Night Eighties + IIDXSERIES"
booru = "beatmania_iidx_13_distorted"
signature = ["cursor", "selection", "foreground"]

[meta.booru_sites]
danbooru = ["beatmania_iidx_13_distorted", "hinazuki_ririna"]
konachan = []
yande = []
zerochan = []

[colors]
background = "#161818"
foreground = "#e2e2e2"
cursor = "#a5a6a6"
selection_background = "#312522"
ansi = [
  "#222424",
  "#f77b7e",
  "#85b786",
  "#e5b451",
  "#72a5d8",
  "#c895c8",
  "#59c0c0",
  "#c6c6c6",

  "#767777",
  "#ffabaa",
  "#a5d9a5",
  "#ffd78e",
  "#93c5fb",
  "#ebb5ea",
  "#7de2e2",
  "#eeeeee",
]
