[meta]
name = "konoha"
native_names = ["恋刃", "コノハ"]
ansi_source = "Catppuccin Macchiato + SDVX"
booru = "konoha_(sound_voltex)"
signature = ["cursor", "selection", "foreground"]

[meta.booru_sites]
konachan = "konoha"

[colors]
background = "#201515"
foreground = "#f6ddd3"
cursor = "#d14e55"
selection_background = "#8c151d"
ansi = [
  "#2d2120",
  "#e9838c",
  "#baae4e",
  "#eeae78",
  "#b790dd",
  "#d593ae",
  "#8dbd87",
  "#d7c1c1",

  "#857372",
  "#fbacb3",
  "#d9cf7f",
  "#ffd5b3",
  "#d3b6ed",
  "#ffb0ce",
  "#aedfa8",
  "#ffe9e8",
]
