[meta]
name = "pastel-kun"
native_names = ["パステルくん", "ぱすてるくん"]
ansi_source = "Catppuccin Macchiato + REFLEC"
booru = "pastel-kun"
signature = ["cursor", "ansi2", "ansi11"]

[meta.booru_sites]
konachan = []
yande = []
zerochan = []

[colors]
background = "#17171f"
foreground = "#e2e1f3"
cursor = "#b7bcff"
selection_background = "#4a3a37"
ansi = [
  "#23232b",
  "#e384a4",
  "#63c052",
  "#d7bc74",
  "#869ee8",
  "#bb9ace",
  "#7ab9d2",
  "#c7c5d0",

  "#777680",
  "#f3adc3",
  "#a1d8ba",
  "#e4e435",
  "#b0c0f4",
  "#e6b4ff",
  "#9edaf4",
  "#eeecfe",
]
