name: ttheme market

on:
  push:
    paths: ["palettes/**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: kecan0406/ttheme/market@v1
